name: 24/7 WhatsApp Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' # සෑම පැය 6කට වරක් auto restart වේ

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run Bot
        run: node index.js
        timeout-minutes: 350 # පැය 6කට ආසන්න කාලයක් රන් වේ
